language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
          after_success:
            - coveralls
        - python: 3.6
          env: TOXENV=docs

install:
    - travis_retry pip install tox

script:
    - travis_retry tox
