language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=cover
        - python: 2.7
          env:
            - TOXENV=py27
            - END_TO_END=1
        - python: 2.7
          env:
            - TOXENV=py27-configparser
            - END_TO_END=1

install:
    - travis_retry pip install tox

script:
    - travis_retry tox

