language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=cover
        - python: 3.6
          env:
            - TOXENV=py36

install:
    - travis_retry pip install tox

script:
    - travis_retry tox
