language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
          after_success:
            - pip install coveralls
            - coveralls
        - python: 3.6
          env: TOXENV=docs

install:
    - pip install tox tox-travis

script:
    - tox
